version: '3.8'
services:
 nginx:
   container_name: spring-petclinic-nginx
   build: ./spring-petclinic-nginx
   image: adamcoakley/team-magenta-group-two:nginx
   restart: unless-stopped
   networks:
     -  petclinic-net
   ports:
     - "80:80"
   volumes:
    -  type: bind
       source: ./spring-petclinic-nginx/nginx.conf
       target: /etc/nginx/nginx.conf
 frontend:
   container_name: spring-petclinic-angular
   build: ./spring-petclinic-angular
   image: adamcoakley/team-magenta-group-two:frontend
   restart: unless-stopped
   deploy:
     replicas: 1
   depends_on:
     - backend
   networks:
     - petclinic-net
  # ports:
   #  - "8080:8080"
 backend:
   build: ./spring-petclinic-rest
   image: adamcoakley/team-magenta-group-two:backend
   container_name: spring-petclinic-rest
   restart: unless-stopped
   deploy:
     replicas: 1
   networks:
     - petclinic-net
   ports:
     - "9966:9966"
 db:
    build: ./spring-petclinic-db
    image: adamcoakley/team-magenta-group-two:petclinic-db
    container_name: petclinic-db
    restart: always
    environment:
      MYSQL_DATABASE: 'petclinic'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - petclinic-db:/var/lib/mysql
# Names our volume
volumes:
  petclinic-db:
networks:
  petclinic-net:
      
